import test from 'node:test';
import assert from 'node:assert/strict';

process.env.NODE_ENV = 'test';
const { server } = await import('../src/server.js');

test('authenticated sale and result publishing workflow', async (context) => {
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  context.after(() => server.close());
  const base = `http://127.0.0.1:${server.address().port}`;
  const login = async (phone, password) => {
    const response = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone, password }) });
    assert.equal(response.status, 200); return (await response.json()).token;
  };
  const seller = await login('9000000004', 'Seller@123');
  const admin = await login('9000000001', 'Admin@123');
  const distributor = await login('9000000002', '1111122222');
  const resultDate = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
  const settingsWithoutPassword = await fetch(`${base}/api/settings`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ schemePrizes: { FOUR_EXACT: 600000 } }) });
  assert.equal(settingsWithoutPassword.status, 403);
  const resultWithoutPassword = await fetch(`${base}/api/draws`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ winningNumber: '1234', boardId: 'kerala', showId: 'all-day', resultDate }) });
  assert.equal(resultWithoutPassword.status, 403);
  const prizeSettingsResponse = await fetch(`${base}/api/settings`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ schemePrizes: { FOUR_EXACT: 600000, TWO_STANDARD: 1500 }, actionPassword: 'Admin@123' }) });
  assert.equal(prizeSettingsResponse.status, 200);
  const prizeSettings = await prizeSettingsResponse.json();
  assert.equal(prizeSettings.schemes.FOUR_DIGIT.prizes.four, 600000);
  assert.equal(prizeSettings.schemes.TWO_DIGIT_STANDARD.prize, 1500);
  const catalogResponse = await fetch(`${base}/api/settings/scheme-catalog`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ name: 'KL 3-15K', pattern: 'ABC', fiveDigitPrize: 0, fourDigitPrize: 500000, threeDigitPrize: 15000, twoDigitPrize: 2000, singleDigitPrize: 500, defaultRate: 30, minimumRate: 25, mrp: 35, actionPassword: 'Admin@123' }) });
  assert.equal(catalogResponse.status, 201);
  const catalogScheme = await catalogResponse.json();
  assert.equal(catalogScheme.name, 'KL 3-15K');
  assert.equal(catalogScheme.threeDigitPrize, 15000);
  const priceUpdateResponse = await fetch(`${base}/api/settings/scheme-catalog`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ id: catalogScheme.id, defaultRate: 31, minimumRate: 26, mrp: 36, actionPassword: 'Admin@123' }) });
  assert.equal(priceUpdateResponse.status, 200);
  const priceUpdatedScheme = await priceUpdateResponse.json();
  assert.equal(priceUpdatedScheme.minimumRate, 26);
  assert.equal(priceUpdatedScheme.mrp, 36);
  const boardConfigResponse = await fetch(`${base}/api/settings/boards/config`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ boardId: 'dear', schemeIds: ['scheme-a', 'scheme-3d-30-15k'], schedules: [{ label: 'Morning', startTime: '09:00', endTime: '11:00', enabled: true }, { label: 'Afternoon', startTime: '13:00', endTime: '15:00', enabled: true }, { label: 'Evening', startTime: '17:00', endTime: '19:00', enabled: true }], actionPassword: 'Admin@123' }) });
  assert.equal(boardConfigResponse.status, 200);
  const configuredBoard = await boardConfigResponse.json();
  assert.equal(configuredBoard.schedules.length, 3);
  assert.equal(configuredBoard.schemeIds.length, 9);
  assert.equal(configuredBoard.schemeIds.includes('scheme-a'), true);
  assert.equal(configuredBoard.schemeIds.includes('scheme-4d-20-1l'), false);
  const distributorResponse = await fetch(`${base}/api/users`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ role: 'DISTRIBUTOR', name: 'New Distributor', phone: '9111111111', password: 'Welcome@123', lotCodeId: 'dear', catalogSchemeRates: { 'scheme-3d-30-15k': { enabled: true, rate: 30 } }, actionPassword: 'Admin@123' }) });
  assert.equal(distributorResponse.status, 201);
  const createdDistributor = await distributorResponse.json();
  assert.equal(createdDistributor.role, 'DISTRIBUTOR');
  assert.deepEqual(createdDistributor.lotCodeIds, ['dear']);
  assert.equal(createdDistributor.catalogSchemeRates['scheme-3d-30-15k'].rate, 30);
  assert.equal(createdDistributor.schemeRates.ONE_STANDARD.rate, 13);
  assert.equal(createdDistributor.lotCodeGraceMinutes.dear.show2, 0);
  const distributorSettingsResponse = await fetch(`${base}/api/users/distributor-settings`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ distributorId: createdDistributor.id, lotCodeId: 'kerala', catalogSchemeRates: { 'scheme-4d-20-1l': { enabled: true, rate: 25 } }, graceMinutes: { show2: 2 }, actionPassword: 'Admin@123' }) });
  assert.equal(distributorSettingsResponse.status, 200);
  const updatedDistributor = await distributorSettingsResponse.json();
  assert.deepEqual(updatedDistributor.lotCodeIds, ['dear', 'kerala']);
  assert.equal(updatedDistributor.catalogSchemeRates['scheme-4d-20-1l'].rate, 25);
  assert.equal(updatedDistributor.schemeRates.TWO_STANDARD.rate, 15);
  assert.equal(updatedDistributor.lotCodeGraceMinutes.kerala.show2, 2);
  const createdDistributorToken = await login('9111111111', 'Welcome@123');
  const scopedSellerResponse = await fetch(`${base}/api/users`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${createdDistributorToken}` }, body: JSON.stringify({ role: 'SELLER', name: 'Lot Scoped Seller', phone: '9111111112', password: 'Seller@456' }) });
  assert.equal(scopedSellerResponse.status, 201);
  const scopedSellerAccount = await scopedSellerResponse.json();
  const scopedSellerToken = await login('9111111112', 'Seller@456');
  const scopedSellerDashboardResponse = await fetch(`${base}/api/dashboard`, { headers: { authorization: `Bearer ${scopedSellerToken}` } });
  assert.equal(scopedSellerDashboardResponse.status, 200);
  const scopedSellerDashboard = await scopedSellerDashboardResponse.json();
  const universalSchemeIds = ['scheme-a', 'scheme-b', 'scheme-c', 'scheme-all-single', 'scheme-ab', 'scheme-ac', 'scheme-bc', 'scheme-all-doubles'];
  assert.deepEqual(Object.fromEntries(scopedSellerDashboard.boards.map((item) => [item.id, item.schemeIds])), {
    dear: [...universalSchemeIds, 'scheme-3d-30-15k'],
    kerala: [...universalSchemeIds, 'scheme-4d-20-1l']
  });
  const belowMinimumRateResponse = await fetch(`${base}/api/users/distributor-settings`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ distributorId: createdDistributor.id, lotCodeId: 'kerala', catalogSchemeRates: { 'scheme-3d-30-15k': { enabled: true, rate: 23 } }, actionPassword: 'Admin@123' }) });
  assert.equal(belowMinimumRateResponse.status, 400);
  const ticketResponse = await fetch(`${base}/api/tickets`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ boardId: 'kerala', catalogSchemeId: 'scheme-4d-20-1l', number: '1234', scheme: 'FOUR_DIGIT', quantity: 2 }) });
  assert.equal(ticketResponse.status, 201);
  const unassignedPremium = await fetch(`${base}/api/tickets`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ boardId: 'kerala', catalogSchemeId: 'scheme-a', number: '34', scheme: 'TWO_DIGIT_PREMIUM', quantity: 1 }) });
  assert.equal(unassignedPremium.status, 403);
  const billResponse = await fetch(`${base}/api/tickets/batch`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ items: [{ boardId: 'kerala', catalogSchemeId: 'scheme-3d-30-15k', number: '234', scheme: 'THREE_DIGIT', quantity: 5 }, { boardId: 'kerala', catalogSchemeId: 'scheme-bc', number: '34', scheme: 'TWO_DIGIT_STANDARD', quantity: 3 }] }) });
  assert.equal(billResponse.status, 201);
  const bill = await billResponse.json();
  assert.equal(bill.quantity, 8);
  assert.equal(bill.total, 195);
  assert.match(bill.bill.billNumber, /^KL-\d{2}-[A-Z]{3}-0002$/);
  assert.equal(bill.bill.items.length, 2);
  const recentBillsResponse = await fetch(`${base}/api/bills/recent`, { headers: { authorization: `Bearer ${seller}` } });
  assert.equal(recentBillsResponse.status, 200);
  const recentBills = await recentBillsResponse.json();
  assert.equal(recentBills[0].billNumber, bill.bill.billNumber);
  const postSalePrizeChange = await fetch(`${base}/api/settings/scheme-catalog`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ id: 'scheme-4d-20-1l', defaultRate: 25, minimumRate: 11, mrp: 25, fourDigitPrize: 999999, threeDigitPrize: 0, twoDigitPrize: 0, singleDigitPrize: 0, actionPassword: 'Admin@123' }) });
  assert.equal(postSalePrizeChange.status, 200);
  const forbidden = await fetch(`${base}/api/draws`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ winningNumber: '1234' }) });
  assert.equal(forbidden.status, 403);
  const allSchemesResponse = await fetch(`${base}/api/tickets/batch`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ items: [{ boardId: 'kerala', catalogSchemeId: 'scheme-all-single', number: '9', scheme: 'ONE_DIGIT_STANDARD', quantity: 5 }, { boardId: 'kerala', catalogSchemeId: 'scheme-all-doubles', number: '99', scheme: 'TWO_DIGIT_STANDARD', quantity: 10 }] }) });
  assert.equal(allSchemesResponse.status, 201);
  const allSchemesBill = await allSchemesResponse.json();
  assert.equal(allSchemesBill.itemCount, 6);
  assert.equal(allSchemesBill.quantity, 45);
  assert.equal(allSchemesBill.total, 645);
  assert.deepEqual(allSchemesBill.tickets.slice(0, 3).map((item) => item.catalogPattern), ['A', 'B', 'C']);
  assert.deepEqual(allSchemesBill.tickets.slice(3).map((item) => item.catalogPattern), ['AB', 'AC', 'BC']);
  assert.deepEqual(allSchemesBill.tickets.map((item) => item.catalogSchemeName), ['1A', '1B', '1C', '2AB', '2AC', '2BC']);
  const previewResponse = await fetch(`${base}/api/reports/result-preview`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ winningNumber: '1234', boardId: 'kerala', showId: 'all-day', resultDate }) });
  assert.equal(previewResponse.status, 200);
  const preview = await previewResponse.json();
  assert.equal(preview.totalPrizes, 278000);
  assert.equal(preview.projectedProfit, -277110);
  assert.equal(preview.status, 'LOSS');
  assert.equal(preview.meetsMinimumProfit, false);
  assert.equal(preview.distributorOutcomes.length, 2);
  const demoDistributorPreview = preview.distributorOutcomes.find((item) => item.name === 'Demo Distributor');
  assert.equal(demoDistributorPreview.netOutcome, -278000);
  const candidatesResponse = await fetch(`${base}/api/reports/result-candidates?boardId=kerala&showId=all-day&resultDate=${resultDate}`, { headers: { authorization: `Bearer ${admin}` } });
  assert.equal(candidatesResponse.status, 200);
  const candidates = await candidatesResponse.json();
  assert.equal(candidates.candidates.length, 1);
  assert.equal(candidates.candidates[0].winningNumber, '1234');
  const rejectedBelowTarget = await fetch(`${base}/api/draws`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ winningNumber: '1234', boardId: 'kerala', showId: 'all-day', resultDate, actionPassword: 'Admin@123' }) });
  assert.equal(rejectedBelowTarget.status, 409);
  const blockedDraw = await fetch(`${base}/api/draws`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ winningNumber: '1234', boardId: 'kerala', showId: 'all-day', resultDate, actionPassword: 'Admin@123', overrideBelowTarget: true, overrideReason: 'Approved test override' }) });
  assert.equal(blockedDraw.status, 201);
  const belowTargetDraw = await blockedDraw.json();
  assert.equal(belowTargetDraw.belowTarget, true);
  assert.equal(belowTargetDraw.preview.projectedProfit, -277110);
  const duplicateDrawResponse = await fetch(`${base}/api/draws`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ winningNumber: '9999', boardId: 'kerala', showId: 'all-day', resultDate, actionPassword: 'Admin@123' }) });
  assert.equal(duplicateDrawResponse.status, 409);
  const saleAfterLockedResult = await fetch(`${base}/api/tickets`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ boardId: 'kerala', catalogSchemeId: 'scheme-a', number: '1', scheme: 'ONE_DIGIT_STANDARD', quantity: 1 }) });
  assert.equal(saleAfterLockedResult.status, 409);
  const ticketsResponse = await fetch(`${base}/api/tickets`, { headers: { authorization: `Bearer ${seller}` } });
  const tickets = await ticketsResponse.json();
  assert.equal(tickets[0].status, 'WIN');
  assert.equal(tickets[0].prize, 200000);
  const dashboardResponse = await fetch(`${base}/api/dashboard`, { headers: { authorization: `Bearer ${admin}` } });
  const dashboard = await dashboardResponse.json();
  const performance = dashboard.distributorPerformance.find((item) => item.distributorId === 'dist-1');
  assert.equal(performance.prizeExposure, 278000);
  assert.equal(performance.status, 'LOSS');
  const mixedLotBill = await fetch(`${base}/api/tickets/batch`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ items: [{ boardId: 'kerala', catalogSchemeId: 'scheme-a', number: '1', scheme: 'ONE_DIGIT_STANDARD', quantity: 1 }, { boardId: 'dear', catalogSchemeId: 'scheme-a', number: '2', scheme: 'ONE_DIGIT_STANDARD', quantity: 1 }] }) });
  assert.equal(mixedLotBill.status, 400);
  const weeklyBefore = await fetch(`${base}/api/reports/weekly-accounts?weekStart=${resultDate}`, { headers: { authorization: `Bearer ${admin}` } });
  assert.equal(weeklyBefore.status, 200);
  const weeklyAccounts = await weeklyBefore.json();
  assert.equal(weeklyAccounts.rows.find((item) => item.distributorId === 'dist-1').quantity, 55);
  const weeklyPayment = await fetch(`${base}/api/weekly-payments`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ distributorId: 'dist-1', weekStart: resultDate, amount: 100, reference: 'Cash', actionPassword: 'Admin@123' }) });
  assert.equal(weeklyPayment.status, 201);
  const paymentData = await weeklyPayment.json();
  assert.equal(paymentData.accounts.rows.find((item) => item.distributorId === 'dist-1').received, 100);
  const dailyExpense = await fetch(`${base}/api/daily-expenses`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ expenseDate: resultDate, amount: 25, note: 'Office expense', actionPassword: 'Admin@123' }) });
  assert.equal(dailyExpense.status, 201);
  const expenseData = await dailyExpense.json();
  assert.equal(expenseData.accounts.totalExpenses, 25);
  assert.equal(expenseData.accounts.days.find((item) => item.date === resultDate).expenses, 25);
  assert.equal(expenseData.accounts.finalNetAmount, expenseData.accounts.totalSales - expenseData.accounts.totalPrizes - 25);
  const distributorWeekly = await fetch(`${base}/api/reports/distributor-weekly?weekStart=${resultDate}`, { headers: { authorization: `Bearer ${distributor}` } });
  assert.equal(distributorWeekly.status, 200);
  const distributorAccounts = await distributorWeekly.json();
  assert.equal(distributorAccounts.quantity, 55);
  assert.equal(distributorAccounts.customerSales > 0, true);
  assert.equal(distributorAccounts.sellerRows.some((item) => item.sellerId === 'seller-1'), true);
  const sellerPayment = await fetch(`${base}/api/seller-payments`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${distributor}` }, body: JSON.stringify({ sellerId: 'seller-1', weekStart: resultDate, amount: 10, reference: 'Cash' }) });
  assert.equal(sellerPayment.status, 201);
  const sellerPaymentData = await sellerPayment.json();
  assert.equal(sellerPaymentData.accounts.sellerRows.find((item) => item.sellerId === 'seller-1').received, 10);
  const distributorDashboardResponse = await fetch(`${base}/api/dashboard`, { headers: { authorization: `Bearer ${distributor}` } });
  const distributorDashboard = await distributorDashboardResponse.json();
  assert.equal(Array.isArray(distributorDashboard.recentDraws), true);
  assert.equal(distributorDashboard.boards.every((board) => board.id === 'kerala'), true);
  const percentageSeller = await fetch(`${base}/api/users`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${distributor}` }, body: JSON.stringify({ role: 'SELLER', name: 'Percentage Seller', phone: '9222222222', password: 'Seller@456', commissionPercentage: 50 }) });
  assert.equal(percentageSeller.status, 201);
  const percentageSellerAccount = await percentageSeller.json();
  assert.equal(percentageSellerAccount.commissionPercentage, 50);
  const updatedSellerCommission = await fetch(`${base}/api/users/seller-commission`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${distributor}` }, body: JSON.stringify({ sellerId: percentageSellerAccount.id, commissionPercentage: 25 }) });
  assert.equal(updatedSellerCommission.status, 200);
  assert.equal((await updatedSellerCommission.json()).commissionPercentage, 25);
  const excessiveSellerPercentage = await fetch(`${base}/api/users`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${distributor}` }, body: JSON.stringify({ role: 'SELLER', name: 'Invalid Seller', phone: '9333333333', password: 'Seller@456', commissionPercentage: 50.01 }) });
  assert.equal(excessiveSellerPercentage.status, 400);
  const rejectedSubDistributor = await fetch(`${base}/api/users`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${distributor}` }, body: JSON.stringify({ role: 'SUB_DISTRIBUTOR', name: 'No Tier', phone: '9444444444', password: 'Seller@456' }) });
  assert.equal(rejectedSubDistributor.status, 403);
  const bonusAtMaximum = await fetch(`${base}/api/bonus-rules`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ beneficiaryId: 'dist-1', enabled: true, targetSales: 0, percentage: 50, actionPassword: 'Admin@123' }) });
  assert.equal(bonusAtMaximum.status, 201);
  const bonusAboveMaximum = await fetch(`${base}/api/bonus-rules`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ beneficiaryId: 'dist-1', enabled: true, targetSales: 0, percentage: 50.01, actionPassword: 'Admin@123' }) });
  assert.equal(bonusAboveMaximum.status, 400);
  const directSellerResponse = await fetch(`${base}/api/users`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ role: 'SELLER', name: 'Admin Direct Seller', phone: '9555555555', password: 'Seller@789', lotCodeId: 'kerala', catalogSchemeRates: { 'scheme-a': { enabled: true, rate: 10.6 } }, commissionPercentage: 20, actionPassword: 'Admin@123' }) });
  assert.equal(directSellerResponse.status, 201);
  const directSellerAccount = await directSellerResponse.json();
  assert.equal(directSellerAccount.parentId, 'admin-1');
  assert.equal(directSellerAccount.role, 'SELLER');
  assert.equal(directSellerAccount.commissionPercentage, 20);
  const directSeller = await login('9555555555', 'Seller@789');
  const directSellerDashboardResponse = await fetch(`${base}/api/dashboard`, { headers: { authorization: `Bearer ${directSeller}` } });
  assert.equal(directSellerDashboardResponse.status, 200);
  const directSellerDashboard = await directSellerDashboardResponse.json();
  assert.deepEqual(directSellerDashboard.boards.map((item) => item.id), ['kerala']);
  assert.equal(directSellerDashboard.schemeCatalog.some((item) => item.id === 'scheme-a'), true);
  const directSellerCommission = await fetch(`${base}/api/users/seller-commission`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ sellerId: directSellerAccount.id, commissionPercentage: 30, actionPassword: 'Admin@123' }) });
  assert.equal(directSellerCommission.status, 200);
  assert.equal((await directSellerCommission.json()).commissionPercentage, 30);
  const directSellerWeekly = await fetch(`${base}/api/reports/weekly-accounts?weekStart=${resultDate}`, { headers: { authorization: `Bearer ${admin}` } });
  const directSellerWeeklyData = await directSellerWeekly.json();
  assert.equal(directSellerWeeklyData.rows.some((item) => item.distributorId === directSellerAccount.id && item.role === 'SELLER'), true);
  const sellerReportsResponse = await fetch(`${base}/api/reports/sales`, { headers: { authorization: `Bearer ${seller}` } });
  assert.equal(sellerReportsResponse.status, 200);
  const sellerReports = await sellerReportsResponse.json();
  assert.equal(sellerReports.length, 1);
  assert.match(sellerReports[0].reportId, /^REP-/);
  assert.equal(sellerReports[0].status, 'FINALIZED');
  assert.equal(sellerReports[0].winningNumber, '1234');
  const distributorReportsResponse = await fetch(`${base}/api/reports/sales`, { headers: { authorization: `Bearer ${distributor}` } });
  assert.equal(distributorReportsResponse.status, 200);
  assert.equal((await distributorReportsResponse.json()).every((item) => item.distributorId === 'dist-1'), true);
  const reportDetailResponse = await fetch(`${base}/api/reports/sale?reportId=${sellerReports[0].id}`, { headers: { authorization: `Bearer ${seller}` } });
  assert.equal(reportDetailResponse.status, 200);
  const reportDetail = await reportDetailResponse.json();
  assert.equal(reportDetail.entries[0].sequence > reportDetail.entries.at(-1).sequence, true);
  assert.equal(reportDetail.entries.every((item) => /^\d{2}:\d{2}:\d{2}$/.test(item.time)), true);
  const sellerSuiteResponse = await fetch(`${base}/api/reports/seller-suite?reportId=${sellerReports[0].id}`, { headers: { authorization: `Bearer ${seller}` } });
  assert.equal(sellerSuiteResponse.status, 200);
  const sellerSuite = await sellerSuiteResponse.json();
  assert.deepEqual(sellerSuite.menu, ['ENTRY', 'ITEM', 'SALES', 'WINNING', 'PAYMENT', 'BILL_WINNING', 'SUMMARY']);
  assert.equal(sellerSuite.itemReport.reduce((sum, item) => sum + item.quantity, 0), sellerSuite.summaryReport.quantity);
  assert.equal(sellerSuite.paymentReport.balance, sellerSuite.paymentReport.sales - sellerSuite.paymentReport.prize);
  assert.equal(sellerSuite.billWinningReport.length > 0, true);
  const forbiddenCorrection = await fetch(`${base}/api/reports/sale-entry`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${seller}` }, body: JSON.stringify({ reportId: reportDetail.id, transactionId: reportDetail.entries.at(-1).transactionId, enteredNumber: '9999', quantity: 2, reason: 'Wrong number entered', actionPassword: 'Seller@123' }) });
  assert.equal(forbiddenCorrection.status, 403);
  const correctedResponse = await fetch(`${base}/api/reports/sale-entry`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ reportId: reportDetail.id, transactionId: reportDetail.entries.at(-1).transactionId, enteredNumber: '9999', quantity: 2, reason: 'Wrong number entered', actionPassword: 'Admin@123' }) });
  assert.equal(correctedResponse.status, 200);
  const corrected = await correctedResponse.json();
  assert.equal(corrected.entries.at(-1).enteredNumber, '9999');
  assert.equal(corrected.corrections.some((item) => item.oldValue === '1234' && item.newValue === '9999'), true);
  const deleteAttempt = await fetch(`${base}/api/reports/sale?reportId=${reportDetail.id}`, { method: 'DELETE', headers: { authorization: `Bearer ${admin}` } });
  assert.equal(deleteAttempt.status, 404);
  const ownPasswordChange = await fetch(`${base}/api/me/password`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${scopedSellerToken}` }, body: JSON.stringify({ currentPassword: 'Seller@456', newPassword: 'Changed@456' }) });
  assert.equal(ownPasswordChange.status, 200);
  const expiredAfterOwnChange = await fetch(`${base}/api/me`, { headers: { authorization: `Bearer ${scopedSellerToken}` } });
  assert.equal(expiredAfterOwnChange.status, 401);
  const changedSellerToken = await login('9111111112', 'Changed@456');
  const adminPasswordReset = await fetch(`${base}/api/users/password-reset`, { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${admin}` }, body: JSON.stringify({ userId: scopedSellerAccount.id, newPassword: 'Reset@456', actionPassword: 'Admin@123' }) });
  assert.equal(adminPasswordReset.status, 200);
  const expiredAfterAdminReset = await fetch(`${base}/api/me`, { headers: { authorization: `Bearer ${changedSellerToken}` } });
  assert.equal(expiredAfterAdminReset.status, 401);
  await login('9111111112', 'Reset@456');
});
